### ISSUE TITLE
Questions about the four-zone cone

### ISSUE THREAD

**Issue by Xuheyi** [arashazimi0032/Improved-ORB-SLAM3-Key-Frame-selection#2]
Dear author, I did not understand when studying your paper “PKS”, in which it says to build a four-zone cone, but I can only find three color-differentiated areas from the figure. however, in his paper (Hosseininaveh et al., 2012) the cone area has four colors. Please tell me that what are the four regions of the four-area cone in your paper? Thank you very much!

**Comment by fightmoney** [comment]
我也有同样的问题，请问你理解了吗？

**Comment by arashazimi0032** [comment]
The fourth area is outside the last color, that is, the area after the last color layer.
Blue is the first area 
Yellow is the second one
Red is the third one
And The area after the red color up to the angle of 90 degrees is the fourth area.
