### ISSUE TITLE
Question about the relationship between the main axis of the four-zone cone and the position of the 3D point

### ISSUE THREAD

**Issue by Xuheyi** [arashazimi0032/Improved-ORB-SLAM3-Key-Frame-selection#3]
Dear author：
        I'm sorry to bother you, I can't understand this sentence in your paper: "Then, for each map point, a four-zone cone is built, with its main axis normal to the surface at the point location" Can you explain the relationship between the main axis of the four-area cone and the map point （3D point）, I can't understand their position relationship, thank you very much!

**Comment by arashazimi0032** [comment]
This sentence means that the position of each cone is exactly on the points of the map When we place the main axis of the cone on the 3d point, we have actually formed a cone on the desired point, which is able to divide the view vector of the point into four areas.
