### ISSUE TITLE
Can the code run in RGBD mode?

### ISSUE THREAD

**Issue by YYDS00** [arashazimi0032/Improved-ORB-SLAM3-Key-Frame-selection#4]
Hello, thanks for your work, I would like to ask if this code can run in RGBD mode? I modified it a bit (turned off the IMU) and then ran RGBD mode and still reported an error, do you know why?
![屏幕截图 2022-11-20 170241](https://user-images.githubusercontent.com/94944673/202894019-36408c8b-2b61-418e-a11a-e3ed619b7f9c.png)

**Comment by YYDS00** [comment]
Hi, I have solved the above problem, but now I still get the error when running RGBD mode.
core dumped.

**Comment by YYDS00** [comment]
Hi, I have solved the above problem, but now I still get the error when running RGBD mode.
core dumped.

**Comment by arashazimi0032** [comment]
This code is only designed for the visual-inertial mode and unfortunately it has not yet been extended to other modes It will probably be developed for other systems in the future
